const moules = require("./5.moules")
const {singlePerson,data} = require("./6.modules")
require("./7-mind-grenade")
console.log(moules.jeri)
console.log(moules.onti)
console.log(data)
console.log(singlePerson)